version: '3'
services:
  microservice1:
    environment:
      - NODE_ENV=development
    build:
      context: ./microservice1
      dockerfile: Dockerfile
    volumes:
      - ./microservice1:/usr/src/app
    ports:
      - 3000:3000

  microservice2:
    environment:
      - NODE_ENV=development
    build:
      context: ./microservice2
      dockerfile: Dockerfile
    volumes:
      - ./microservice2:/usr/src/app
    ports:
      - 3001:3000

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672 # default RabbitMQ port
      - 15672:15672 # management UI

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
